### ISSUE TITLE
[Question] ConstantBuffer exposal

### ISSUE THREAD

**Issue by cz-dev-ge** [OptimisticPeach/GardeningGame#1]
Hi @OptimisticPeach,

thanks for sharing your code. I wonder: how did you access the ConstantBuffers.

In `WaterWithEffect.cs` you do the following:

```cs
Buffer[] vsBuffers = WEffect.InternalEffect.ConstantBuffers.Select((a) => a._cbuffer).ToArray();
```

 I read in the README, that you altered MonoGame but could not find the code. I am trying to understand your use of Geometry Shaders for my own implementation but can't get past this point. Did you fork MonoGame and make the ConstantBuffer public?

Cheers,
Georg

**Comment by OptimisticPeach** [comment]
I'm sorry for the vagueness since I haven't touched Monogame in a really long time (Or C# really for that matter), but in general, yes, my modifications would generally just involve making things public so that I could access them directly without going through Monogame. 

Additionally, now that I look at the code in question, I remember diving into the Monogame source code and replicating what it did, which at the time was that. 

If you've any more questions, please reply and I'd be happy to help you to the best of my memory. I have still been working on graphics programming however, so I haven't gotten rusty on that.

**Comment by cz-dev-ge** [comment]
No worries. Happy to get a reply at all :D Did you keep the code changes to MonoGame somewhere or are they included as a DLL only?

**Comment by OptimisticPeach** [comment]
I don't seem to still have the changes to monogame anywhere, but I suggest you make the changes yourself as though they mostly involved making things public. Additionally, that could would've been based off of code for Monogame written in ~2017, and would definitely be at least a couple hundred commits behind.

**Comment by cz-dev-ge** [comment]
Yeah, you're right. Thanks for your help : )
